name: Get Digest

description: Custom GitHub Action to retrieve the digest of the amd64 architecture from a Docker image manifest.

inputs:
  image:
    description: 'The name of the Docker image.'
    required: true
    default: 'nginx:latest'

outputs:
  digest:
    description: 'The digest of the amd64 architecture in the Docker image manifest.'

runs:
  using: 'node12'
  main: 'index.js'