name: Get Substrate Version Workflow
on:
  push:
    branches:
      - main

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get Substrate Version
        uses: your-repo/get-substrate-version-action@v1
        id: substrate_version
        with:
          image_name: rainfall-one/crucible:latest
      
      - name: Print Substrate Version
        run: echo "The version of Substrate is ${{ steps.substrate_version.outputs.version }}"
