name: Get Digest
description: Custom GitHub Action to retrieve the digest of the amd64 architecture from a Docker image manifest.

on:
  pull_request:
    types:
      - closed

inputs:
  image:
    description: 'The name of the Docker image.'
    required: true
    default: 'nginx:latest'

outputs:
  digest:
    description: 'The digest of the amd64 architecture in the Docker image manifest.'

runs:
  using: 'node12'

steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '12'

  - name: Install dependencies
    run: npm install

  - name: Run action
    run: node index.js
